name: instagram_clone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  image_picker: ^1.0.1
  cached_network_image: ^3.2.3

  get_it: ^7.6.0
  flutter_local_notifications: ^15.1.0+1
  shared_preferences: ^2.2.0
  device_info_plus: ^9.0.3

  logger: ^2.0.1


  # firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  cloud_firestore: ^4.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
